CREATE TABLE DADOS (
ID INT IDENTITY PRIMARY KEY,
NOME_ANUNCIO VARCHAR(50)  NOT NULL,
CLIENTE VARCHAR(200) NOT NULL,
DATA_INICIO DATE NOT NULL,
DATA_TERMINO DATE NOT NULL, 
INVESTIMENTO_DIA INT NOT NULL,
);
INSERT INTO DADOS (NOME_ANUNCIO, CLIENTE, DATA_INICIO, DATA_TERMINO, INVESTIMENTO_DIA) VALUES ('PRIMEIRO', 'ABC', '2021-01-01', '2021-05-01', 1);
INSERT INTO DADOS (NOME_ANUNCIO, CLIENTE, DATA_INICIO, DATA_TERMINO, INVESTIMENTO_DIA) VALUES ('SEGUNDO', 'DEF', '2021-01-01', '2021-02-01', 2);
INSERT INTO DADOS (NOME_ANUNCIO, CLIENTE, DATA_INICIO, DATA_TERMINO, INVESTIMENTO_DIA) VALUES ('TERCEIRO', 'GHI', '2021-02-01', '2021-03-01', 3);

CREATE TABLE RELATORIO (
ID INT IDENTITY PRIMARY KEY,
VALOR_TOTAL INT NOT NULL,
QUANTMAX_VISU INT NOT NULL,
QUANTIDADEMAX_CLIQUES INT  NOT NULL,
QUANTIDADEMAX_COMPART INT NOT NULL, 
DADOSID INT,
FOREIGN KEY (DADOSID) REFERENCES DADOS(ID)
);
INSERT INTO RELATORIO (VALOR_TOTAL, QUANTMAX_VISU, QUANTIDADEMAX_CLIQUES, QUANTIDADEMAX_COMPART, DADOSID) VALUES (120, 10240, 1117, 1661, 1);
INSERT INTO RELATORIO (VALOR_TOTAL, QUANTMAX_VISU, QUANTIDADEMAX_CLIQUES, QUANTIDADEMAX_COMPART, DADOSID) VALUES (60, 4960, 546, 79, 2);
INSERT INTO RELATORIO (VALOR_TOTAL, QUANTMAX_VISU, QUANTIDADEMAX_CLIQUES, QUANTIDADEMAX_COMPART, DADOSID) VALUES (90, 7620, 832, 123, 3);

SELECT 
	R.ID AS ID_DO_CLIENTE,
	R.VALOR_TOTAL AS VALORTOTAL_DO_RELATORIO,
	R.QUANTMAX_VISU AS QUANTIDADEVISU_DO_RELATORIO,
	R.QUANTIDADEMAX_CLIQUES AS QUANTIDADECLIQUES_DO_RELATORIO,
	R.QUANTIDADEMAX_COMPART AS QUANTIDADECOMPART_DO_RELATORIO

	FROM
	
	RELATORIO R

	INNER JOIN DADOS D
    ON (D.ID= R.DADOSID)
	WHERE D.DATA_INICIO = '2021-01-01'

INNER JOIN DADOS D
    ON (D.ID= R.DADOSID)
WHERE D.CLIENTE = 'ABC'


